### ISSUE TITLE
Handle species case for Special Level A, etc. for group = "PA"

### ISSUE THREAD

**Issue by j-harbin** [dfo-mar-odis/TBSpayRates#16]

**Comment by j-harbin** [comment]
On the following page https://www.tbs-sct.canada.ca/agreements-conventions/view-visualiser-eng.aspx?id=15#rates-st there is two "Special" levels, one for DA‐CON‐8 and one for ST-COR-2. See below. My guess is that the "special level" is for the classification above. E.g. for the first screen shot it would be appropriate to say SpecialLevelcDA‐CON‐8 (or something like that). @remi-daigle I'm curious your opinion on this one.

![image](https://github.com/dfo-mar-odis/TBSpayRates/assets/58750538/8ea7f3f2-39aa-472f-b25c-a2d4997898d6)

![image](https://github.com/dfo-mar-odis/TBSpayRates/assets/58750538/ef2ca2b6-4c24-406a-9f3f-acdec687194d)

**Comment by remi-daigle** [comment]
Yep, totally agree, but I would have flipped it e.g. DA-CON-8-SpecialLevelC

**Comment by j-harbin** [comment]
Done in commit fca2bc71a588885888a361628f2c1ac627f13794  of dataSPA.
