### ISSUE TITLE
adding group to package data

### ISSUE THREAD

**Issue by MichaelFolkes** [dfo-mar-odis/TBSpayRates#4]
can I suggest adding the vector of groups to the package data so the user can easily know what to search for? Alternatively the group vector could be in the group argument of the function def.  Nice work!

**Comment by remi-daigle** [comment]
Totally possible! Let me see what I can do! (And thank you for using the 'issues' functionality)

**Comment by remi-daigle** [comment]
That was a quick fix!

You can now do:
`data(groups)`
