### ISSUE TITLE
some groups missing (e.g. TC)

### ISSUE THREAD

**Issue by remi-daigle** [dfo-mar-odis/TBSpayRates#5]
I think it's because the word "annual" does not appear in their salary tables.

[This line may be the culprit](https://github.com/dfo-mar-odis/TBSpayRates/blob/e02006764d09e6a599d9dbda0cd7d9f6b8ee1d8e/R/get_salaries.R#L67)

**Comment by remi-daigle** [comment]
This issue is not as simple as initially expected. Some classifications (e.g. EG-2) are listed twice. It'll have to be handled differently like the SH and SV groups that have subgroups

**Comment by j-harbin** [comment]
This has been fixed. In summary there were multiple tables for groups in TC (specifically TI) for aviation, marine, and railway safety. See more comments here: https://github.com/dfo-mar-odis/TBSpayRates/issues/20
