### ISSUE TITLE
classification has awkward use of UTF-8 character

### ISSUE THREAD

**Issue by MichaelFolkes** [dfo-mar-odis/TBSpayRates#6]
being that the classification column uses some characters awkwardly, it makes manipulation difficult.
one example being the hyphen.  for some records it is `-`, others can be `–`. In unicode, these variations are found in the data: 
"<U+2010>", "<U+2011>", "<U+2013>"
same goes for spacing.

This code chunk might come in handy as a starting point to build on within `get_salaries`
```
sal <- get_salaries(groups = "all")

#could put this inside get_salaries
sal$Classification <- iconv(sal$Classification, "UTF-8", "ASCII", "Unicode")

#these are all variations on hyphens:
for(x in c("<U+2010>", "<U+2011>", "<U+2013>")) sal$Classification <- gsub(x, "-", sal$Classification, fixed = TRUE)

#variations on spacing:
for(x in c("<U+00A0>", " ")) sal$Classification <- gsub(x, "", sal$Classification, fixed = TRUE)

#add a zero in front of classification number when it doesn't exist:
sal$Classification <- gsub("[-]([1-9])", "-0\\1", sal$Classification)
```

**Comment by remi-daigle** [comment]
Thanks for the suggested code! I definitely used it as a basis to fix `get_salaries`
